# docker-compose -f ./docker/ambiente-local.yml up --force-recreate -d --build
# docker-compose -f ./docker/ambiente-local.yml down --remove-orphans

version: '3.8'

services:

  ecommerce-orders-api:
    container_name: ecommerce-orders-api
    networks:
      - mongodb-network
    restart: always
    depends_on:
      - mongodb
    build:
      context: ../src
      dockerfile: ./ECommerce.Orders.Api/Dockerfile
    ports:
      - 9042:80
      - 9043:443

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: avanade-user
      ME_CONFIG_BASICAUTH_PASSWORD: psw-avanade
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: user01
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      #ME_CONFIG_MONGODB_URL: mongo://root:psw#Admin@mongo:27017/
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - mongodb-network

  mongodb:
    image: mongo:4.2.23
    container_name: mongodb
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: user01
    #   MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - /mongo-kafka:/data/db
    networks:
      - mongodb-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    hostname: zookeeper
    networks: 
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    networks: 
      - broker-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    networks: 
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

networks: 
    mongodb-network:
      driver: bridge
    broker-kafka:
      driver: bridge

volumes:
  kafka-avanade:



# docker compose exec broker \
#   kafka-topics --create \
#     --topic purchases \
#     --bootstrap-server localhost:9092 \
#     --replication-factor 1 \
#     --partitions 1