name: "Build project"

on:
  pull_request:
    branches:    
      - main
      - 'features/**'
      - '!test/**'      
  push:
    branches:    
      - main
      - 'features/**'
    paths:
      - 'apps/**/**'
            
  workflow_dispatch:

jobs:
  build-orders-service:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/Orders-api/src

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
    
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
  build-email-servcie:
      runs-on: ubuntu-latest
      defaults:
          run:
              working-directory: apps/Orders-email/src

      steps:
          - uses: actions/checkout@v3
          - name: Setup .NET

            uses: actions/setup-dotnet@v3
            with:
                dotnet-version: 8.0.x

          - name: Restore dependencies
            run: dotnet restore

          - name: Build
            run: dotnet build --no-restore
      
